### ISSUE TITLE
Playtesting MVP

### ISSUE THREAD

**Issue by lindtvedtsebastian** [NTNU-IMT3603-PLATFORMER/NTNU-IMT3606-GAME#60]
### General notes
- I like the art style and general feel of the game
- I am sure you have this planned, but implementing some kind of loot (coins, etc) will greatly increase the experience
- I like the addition of the "secret" rooms, it rewards exploration. I guess you are going to place some special currency or something here
- The transformation mechanic seems like a cool concept, looking forward to experiencing that in the future
- Personally I would appreciate health bars on the enemies, as it is a bit difficult to keep track of how much damage you have done as of now
- I think having a tutorial scene/world where the players are introduced to the transformation mechanics would be a great addition, but perhaps this is something that will be made clear in the final version of your game through some kind of progression instead.

### Issues found
I could see that you already have issues added for some of the points that I have here, but il keep them in anyways
- Enemies fly up when you hit them (pretty obvious, but felt like it should be noted for records sake)
- When using the platform that moves up (the elevator of sorts), the player is forcefully jumping
- The animation states gets messed up when wall sliding in some cases. (You can replicate this by wall sliding, jumping off the wall, then jumping back onto the wall)
![wall_glitch](https://user-images.githubusercontent.com/46536611/140475773-a262d0df-dc2c-4737-9c73-fc48a32f81de.png)

- I think there is a death animations playing when transforming to the different "animals", I guess that this animation is just a placeholder for proper transformations, but I wish that the death animation was played when the player dies, instead of being a direct teleport back to start.

### Final thoughts
A great start, keep up the good work. I'm sure this game will turn out great

**Comment by rubenchristoffer** [comment]
Thank you for playtesting and providing feedback for our MVP!

### General notes

> I am sure you have this planned, but implementing some kind of loot (coins, etc) will greatly increase the experience

We have some ideas surrounding this. Right now we are looking at making enemies drop "souls" when they die. 

> I like the addition of the "secret" rooms, it rewards exploration. I guess you are going to place some special currency or something here

We don't know exactly what will be in these rooms, but we liked the idea of having secret rooms as well.

> Personally I would appreciate health bars on the enemies, as it is a bit difficult to keep track of how much damage you have done as of now

We have discussed this in the past, where some group members were for health bars and others were not. We ended up not using health bars for enemies (at least for the MVP). We might add a health bar to the boss(es) though, we'll see. Thanks for the opinionated feedback, we'll take it into consideration :)

> I think having a tutorial scene/world where the players are introduced to the transformation mechanics would be a great addition, but perhaps this is something that will be made clear in the final version of your game through some kind of progression instead.

The idea is to gain a new transformation after each boss as a form of progression, but exactly how the transformation mechanic is explained to the user remains to be seen. We're leaning toward a dedicated tutorial level and maybe having an NPC telling you how it works. 

### Issues found
> I think there is a death animations playing when transforming to the different "animals", I guess that this animation is just a placeholder for proper transformations

Yes, it is simply a placeholder animation for now. 

> I wish that the death animation was played when the player dies, instead of being a direct teleport back to start.

Yes, we will fix this!

The other issues you mentioned have already been fixed or are soon-to-be fixed in upcoming updates. 

Thanks for the feedback, we'll get working on improvements straight away :)
